openapi: 3.0.0
info:
  title: Sistema GIL API
  version: 1.0.0
  description: API REST para gestión inteligente de laboratorios - Centro Minero de Sogamoso - SENA

servers:
  - url: http://127.0.0.1:5000

paths:
  /api/equipos:
    get:
      summary: Listar equipos disponibles
      responses:
        '200':
          description: Lista de equipos
          content:
            application/json:
              schema:
                type: object
                properties:
                  equipos:
                    type: array
                    items:
                      type: object
                      properties:
                        id_equipo:
                          type: integer
                        nombre_equipo:
                          type: string
                        marca:
                          type: string
                        modelo:
                          type: string